//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string EARTH = "earth";
        
        public const string AIR = "air";
        
        public const string WATER = "water";
        
        public const string FIRE = "fire";
        
        public const string FINISH_CASTING = "finish_casting";
        
        public const string ENTERED_CASTING = "entered_casting";
        
        public const string FIRING = "firing";
    }
}
